/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import "time"

type Notification struct {
	Id int32 `json:"id,omitempty"`

	Priority int32 `json:"priority,omitempty"`

	Type_ int32 `json:"type,omitempty"`

	Title string `json:"title,omitempty"`

	Content string `json:"content,omitempty"`

	PosterID int32 `json:"posterID,omitempty"`

	SeenCount int32 `json:"seen_count,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`

	DateExpired time.Time `json:"dateExpired,omitempty"`
}
