/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import "time"

type Notice struct {
	Id int32 `json:"id,omitempty"`

	Type_ int32 `json:"type,omitempty"`

	DateOccur time.Time `json:"dateOccur,omitempty"`

	Title string `json:"title,omitempty"`

	Content []string `json:"content,omitempty"`

	ConfirmMessage string `json:"confirmMessage,omitempty"`

	StudentID int32 `json:"studentID,omitempty"`

	ParentID int32 `json:"parentID,omitempty"`

	TeacherID int32 `json:"teacherID,omitempty"`

	ClassID int32 `json:"classID,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`

	DateExpired time.Time `json:"dateExpired,omitempty"`
}
