/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Statistic struct {

	Id int32 `json:"id,omitempty"`

	Quater int32 `json:"quater,omitempty"`

	StudentID int32 `json:"studentID,omitempty"`

	ClassID int32 `json:"classID,omitempty"`

	Total int32 `json:"total,omitempty"`

	AbsencecDays int32 `json:"absencecDays,omitempty"`

	// Nghi co phep
	RequestedAbsenceDays int32 `json:"requestedAbsenceDays,omitempty"`

	CancelMeals int32 `json:"cancelMeals,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`
}
