/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TuitionFee struct {

	Id int32 `json:"id,omitempty"`

	Quater int32 `json:"quater,omitempty"`

	Paid bool `json:"paid,omitempty"`

	ClassID int32 `json:"classID,omitempty"`

	StudentID int32 `json:"studentID,omitempty"`

	Total int32 `json:"total,omitempty"`

	Tuition int32 `json:"tuition,omitempty"`

	Food int32 `json:"food,omitempty"`

	Bus int32 `json:"bus,omitempty"`

	Refund int32 `json:"refund,omitempty"`

	Other int32 `json:"other,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`
}
