/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AdminStatistic struct {

	Id int32 `json:"id,omitempty"`

	ClassID int32 `json:"classID,omitempty"`

	// the total of student
	TotalStudents int32 `json:"totalStudents,omitempty"`

	// Nghi khong phep
	Absences int32 `json:"absences,omitempty"`

	// Nghi co phep
	RequestedAbsences int32 `json:"requestedAbsences,omitempty"`

	MorningMeals int32 `json:"morningMeals,omitempty"`

	NoonMeals int32 `json:"noonMeals,omitempty"`

	AfternoonMeals int32 `json:"afternoonMeals,omitempty"`

	LateMeals int32 `json:"lateMeals,omitempty"`

	LatePickup int32 `json:"latePickup,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`
}
