/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WeekMenu struct {

	Id int32 `json:"id,omitempty"`

	Week string `json:"week,omitempty"`

	DayMenuID int32 `json:"dayMenuID,omitempty"`

	Note string `json:"note,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`
}
