/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import "time"

type Form struct {
	Id int64 `json:"id,omitempty"`

	// type: 1- nghi hoc, 2- don tre, 3- huy bua
	Type_ int32 `json:"type,omitempty"`

	StudentID int32 `json:"studentID,omitempty"`

	PosterID int32 `json:"posterID,omitempty"`

	PickerName string `json:"pickerName,omitempty"`

	PickerPhone string `json:"pickerPhone,omitempty"`

	PickerPhoto string `json:"pickerPhoto,omitempty"`

	// class: 1- sang, 2- chieu
	ClassTime string `json:"classTime,omitempty"`

	Title string `json:"title,omitempty"`

	Content string `json:"content,omitempty"`

	DateRequest time.Time `json:"dateRequest,omitempty"`

	TimeRequest time.Time `json:"timeRequest,omitempty"`

	// Meal: 1- sang, 2- chieu, 3-xe, 4-ca ngay
	CancelMeal int32 `json:"cancelMeal,omitempty"`

	IsCancelMeal bool `json:"isCancelMeal,omitempty"`

	LateMeal bool `json:"lateMeal,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`
}
