/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Activity struct {
	Id int64 `json:"id,omitempty"`

	ClassID int32 `json:"classID,omitempty"`

	Type_ int32 `json:"type,omitempty"`

	DateOccur string `json:"dateOccur,omitempty"`

	DateExpired string `json:"dateExpired,omitempty"`

	TeacherID int32 `json:"teacherID,omitempty"`

	Title string `json:"title,omitempty"`

	Content string `json:"content,omitempty"`

	Photo1 string `json:"photo1,omitempty"`

	Caption1 string `json:"caption1,omitempty"`

	Photo2 string `json:"photo2,omitempty"`

	Caption2 string `json:"caption2,omitempty"`

	Photo3 string `json:"photo3,omitempty"`

	Caption3 string `json:"caption3,omitempty"`

	Photo4 string `json:"photo4,omitempty"`

	Caption4 string `json:"caption4,omitempty"`

	Photo5 string `json:"photo5,omitempty"`

	Caption5 string `json:"caption5,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`
}
