/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StudentStatus struct {
	Id int32 `json:"id,omitempty"`

	StudentID int32 `json:"studentID,omitempty"`

	StudentName string `json:"studentName,omitempty"`

	SchoolArrival int32 `json:"schoolArrival,omitempty"`

	AbsenceRequested int32 `json:"absenceRequested,omitempty"`

	LatePickup int32 `json:"latePickup,omitempty"`

	MealCancel int32 `json:"mealCancel,omitempty"`

	ParentNotice string `json:"parentNotice,omitempty"`
}
