/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NotificationStatistic struct {

	Id int32 `json:"id,omitempty"`

	NotificationID int32 `json:"notificationID,omitempty"`

	TotalTarget int32 `json:"totalTarget,omitempty"`

	TotalSeenCount int32 `json:"totalSeenCount,omitempty"`

	// So phu huynh chua xem thong bao
	UnseenList []Parent `json:"unseenList,omitempty"`
}
