/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Notice struct {

	Id int32 `json:"id,omitempty"`

	Type_ int32 `json:"type,omitempty"`

	Content string `json:"content,omitempty"`

	ConfirmMessage string `json:"confirmMessage,omitempty"`

	PosterID int32 `json:"posterID,omitempty"`

	ReceiverID int32 `json:"receiverID,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`

	DateExpired string `json:"dateExpired,omitempty"`
}
