/*
 * Demo App
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TuitionPayment struct {

	Id int32 `json:"id,omitempty"`

	Year int32 `json:"year,omitempty"`

	Quarter int32 `json:"quarter,omitempty"`

	StudentID int32 `json:"studentID,omitempty"`

	Paid int32 `json:"paid,omitempty"`

	DatePaid string `json:"date_paid,omitempty"`

	DateNotice string `json:"date_notice,omitempty"`

	DateSeen string `json:"date_seen,omitempty"`

	NoticeCount int32 `json:"noticeCount,omitempty"`

	Note string `json:"note,omitempty"`

	Amount string `json:"amount,omitempty"`

	DateCreated string `json:"dateCreated,omitempty"`
}
